export const processStepStyles = {
  stepContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    zIndex: 2,
    width: '100%',
  },
  stepLayout: (side: 'left' | 'right') => ({
    display: 'flex',
    flexDirection: { xs: 'column', md: 'row' },
    alignItems: { xs: 'center', md: 'center' },
    justifyContent: { xs: 'center', md: 'space-between' },
    width: '100%',
    maxWidth: { xs: '100%', md: 800 },
    mx: 'auto',
    gap: { xs: 2, md: 4 },
    ...(side === 'right' && {
      flexDirection: { xs: 'column', md: 'row-reverse' },
    }),
  }),
  illustrationContainer: (_side: 'left' | 'right') => ({
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexShrink: 0,
    order: { xs: 1, md: 0 },
  }),
  illustration: (color: string) => ({
    width: { xs: 80, sm: 100, md: 150 },
    height: { xs: 80, sm: 100, md: 150 },
    borderRadius: '50%',
    background: `linear-gradient(135deg, ${color}15 0%, ${color}30 100%)`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: color,
    border: `2px solid ${color}40`,
    boxShadow: `0 4px 16px ${color}20`,
    '& .MuiSvgIcon-root': {
      fontSize: { xs: 40, sm: 60, md: 120 },
    },
  }),
  cardContainer: (_side: 'left' | 'right') => ({
    flex: 1,
    maxWidth: { xs: '100%', md: 400 },
    order: { xs: 2, md: 0 },
  }),
  card: (color: string) => ({
    width: '100%',
    background: `linear-gradient(135deg, ${color}10 0%, ${color}05 100%)`,
    border: `2px solid ${color}30`,
    position: 'relative',
    zIndex: 3,
    overflow: 'visible',
    mt: { xs: 1, md: 3 },
    mb: { xs: 1, md: 3 },
  }),
  stepNumber: (color: string, side: 'left' | 'right') => ({
    position: 'absolute',
    top: { xs: -15, md: -20 },
    left: {
      xs: -15,
      md: side === 'left' ? -20 : 'auto',
    },
    right: {
      xs: 'auto',
      md: side === 'left' ? 'auto' : -20,
    },
    width: { xs: 35, md: 50 },
    height: { xs: 35, md: 50 },
    borderRadius: '50%',
    bgcolor: '#ffffff',
    color: color,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 900,
    fontSize: { xs: '1.2rem', md: '1.5rem' },
    boxShadow: `0 4px 15px rgba(0, 0, 0, 0.2), 0 0 0 3px ${color}`,
    zIndex: 999,
    border: `3px solid ${color}`,
  }),
  cardContent: {
    p: { xs: 2, md: 3 },
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    mb: 2,
    flexWrap: 'wrap',
  },
  avatar: (color: string) => ({
    bgcolor: color,
    mr: 2,
    width: { xs: 40, md: 48 },
    height: { xs: 40, md: 48 },
    boxShadow: `0 4px 12px ${color}30`,
  }),
  title: {
    fontWeight: 700,
    fontSize: { xs: '1.1rem', md: '1.5rem' },
  },
  description: {
    mb: 3,
    fontSize: { xs: '0.95rem', md: '1rem' },
  },
  detailItem: {
    display: 'flex',
    alignItems: 'flex-start',
    mb: 1,
  },
  detailBullet: (color: string) => ({
    width: 6,
    height: 6,
    borderRadius: '50%',
    bgcolor: color,
    mr: 2,
    mt: 0.7,
    flexShrink: 0,
  }),
  detailText: {
    fontSize: { xs: '0.85rem', md: '0.875rem' },
  },
};
